version: "3.7"

services:
    php:
        build: # Info to build the Docker image
            context: ./.docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
            dockerfile: PHP83-Dockerfile # Specify the name of the Dockerfile
        ports:
            - 8111:80
        depends_on:
            - redmine
        volumes:
            - ./:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.*

    redmine:
        image: redmine:5.1.1
        ports:
            - "3000:3000"
        environment:
            REDMINE_DB_MYSQL: "mariadb"
            REDMINE_DB_PORT: ""
            REDMINE_DB_USERNAME: "redmine"
            REDMINE_DB_PASSWORD: "redmine"
            REDMINE_DB_DATABASE: "redmine"
            REDMINE_SECRET_KEY_BASE: supersecretkey
            REDMINE_PLUGINS_MIGRATE: true
        depends_on:
            - mariadb
        volumes:
            - ./.docker/redmine_data:/usr/src/redmine/files

    mariadb:
        image: mariadb:10.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "redmine"
            MYSQL_USER: "redmine"
            MYSQL_PASSWORD: "redmine"
        volumes:
            - ./.docker/mariadb_data:/var/lib/mysql

