name: Behat-Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests (Behat with PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php: ["8.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Show docker info
        run: docker compose version

      - name: Build and cache Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start containers
        run: |
          docker compose -f "docker-compose.yml" up -d --build

      - name: Setup PHP with composer
        run: |
          docker compose -f "docker-compose.yml" exec php composer update

      - name: Debug docker files
        run: |
          docker compose -f "docker-compose.yml" exec php tree ./.docker

      - name: Run behat tests
        run: docker compose -f "docker-compose.yml" exec php composer behat

      - name: Stop containers
        run: |
          docker compose -f "docker-compose.yml" down
